"""child_id_activity_logs_name_index

Revision ID: 17715d863cba
Revises: 285a346288d3
Create Date: 2026-04-11 10:59:55.102735

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '17715d863cba'
down_revision: Union[str, Sequence[str], None] = '285a346288d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('child_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'activity_logs', 'children', ['child_id'], ['id'])
    op.create_index('ix_children_center_name_lower', 'children', ['center_id', sa.literal_column('lower(name)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_children_center_name_lower', table_name='children')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_column('activity_logs', 'child_id')
    # ### end Alembic commands ###
