"""add_photo_legal_columns_l4

Revision ID: 928e87c15f97
Revises: 3000c1a34dd7
Create Date: 2026-04-19 21:03:22.407254

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '928e87c15f97'
down_revision: Union[str, Sequence[str], None] = '3000c1a34dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('child_id', sa.UUID(), nullable=True))
    op.add_column('photos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'photos', 'children', ['child_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'deleted_at')
    op.drop_column('photos', 'child_id')
    # ### end Alembic commands ###
