"""add_ai_api_logs_legal_l5

Revision ID: eb460b44f0f4
Revises: c148259a0894
Create Date: 2026-04-19 20:54:29.591427

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eb460b44f0f4'
down_revision: Union[str, Sequence[str], None] = 'c148259a0894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_api_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=50), nullable=False),
    sa.Column('input_token_count', sa.Float(), nullable=True),
    sa.Column('output_token_count', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_api_logs')
    # ### end Alembic commands ###
