/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#3c4a3d',
        'on-tertiary-fixed': '#1f1b16',
        'tertiary-fixed': '#ebe1d8',
        'tertiary-container': '#a39b93',
        'primary-fixed-dim': '#ffb598',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#572610',
        'secondary-fixed': '#d6e7d5',
        'primary-fixed': '#ffdbce',
        'surface-container-high': '#ece7e4',
        'surface-bright': '#fef8f5',
        'on-secondary-fixed': '#111f14',
        'surface-dim': '#ded9d6',
        'surface-container-low': '#f8f3ef',
        'on-secondary-container': '#59685a',
        'inverse-primary': '#ffb598',
        'inverse-on-surface': '#f5f0ec',
        'surface-container-highest': '#e7e1de',
        'outline-variant': '#d8c2ba',
        'on-tertiary-fixed-variant': '#4c463f',
        'error-container': '#ffdad6',
        surface: '#fef8f5',
        'secondary-fixed-dim': '#bacbba',
        'on-secondary': '#ffffff',
        error: '#ba1a1a',
        'tertiary-fixed-dim': '#cec5bc',
        secondary: '#536254',
        'on-primary': '#ffffff',
        tertiary: '#645d56',
        'surface-container': '#f2edea',
        'inverse-surface': '#32302e',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#d38b6e',
        'on-primary-fixed-variant': '#6e3821',
        'on-surface': '#1d1b1a',
        'on-surface-variant': '#53433e',
        'surface-tint': '#8a4f36',
        'on-tertiary-container': '#38332d',
        'secondary-container': '#d6e7d5',
        background: '#fef8f5',
        'on-primary-fixed': '#370e00',
        'on-background': '#1d1b1a',
        'surface-variant': '#e7e1de',
        primary: '#8a4f36',
        outline: '#85736d',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm: '0.5rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
      boxShadow: {
        ambient: '0 12px 40px rgba(83,67,62,0.06)',
        'ambient-up': '0 -12px 40px rgba(83,67,62,0.06)',
      },
    },
  },
  plugins: [],
};
